version: "3.8"
services:
  app:
    build: .
    container_name: fibonacci-calculator-php
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - fibonacci-calculator-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: fibonacci-calculator-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fibonacci-calculator-network

networks:
  fibonacci-calculator-network:
    driver: bridge