version: "3.8"
services:
  app:
    build: .
    container_name: flix-mobility-php
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - flix-mobility-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: flix-mobility-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - flix-mobility-network

networks:
  flix-mobility-network:
    driver: bridge